import { getAnimationKeyframesString, toPascalCase } from '../utils/componentHelpers';

/**
 * Genera el script de cliente encargado de activar las animaciones
 */
const getAstroClientScript = (): string => {
  return `
<script>
  ${getAnimationKeyframesString()}

  document.querySelectorAll('svg[data-animation]').forEach((svg) => {
    const type = svg.getAttribute('data-animation');
    if (!type || !ANIMATION_KEYFRAMES[type]) return;

    const duration = parseInt(svg.getAttribute('data-animation-duration') || '1000');
    const iteration = svg.getAttribute('data-animation-iteration') || 'infinite';

    svg.animate(ANIMATION_KEYFRAMES[type], {
      duration,
      iterations: iteration === 'infinite' ? Infinity : parseInt(iteration),
    });
  });
</script>`;
};

/**
 * Genera la lógica del frontmatter (el bloque --- de Astro)
 */
const getAstroFrontmatter = (): string => {
  return `---
import { icons } from './svg-data';

interface Props {
  name: string;
  size?: string | number;
  color?: string;
  variant?: string;
  animation?: 'spin' | 'pulse' | 'bounce' | 'shake' | 'ping' | 'fade' | 'blink';
  class?: string;
}

const { name, size = '1em', color = 'currentColor', variant, animation, class: className } = Astro.props;
const icon = (icons as any)[name];
const sizeValue = typeof size === 'number' ? \`\${size}px\` : size;

let body = icon?.body || '';

if (variant && icon?.variants?.[variant]) {
  Object.entries(icon.variants[variant]).forEach(([orig, repl]) => {
    const escaped = orig.replace(/[.*+?^$\${}()|[\\]\\\\]/g, '\\\\$&');
    body = body.replace(new RegExp(escaped, 'gi'), repl as string);
  });
}

const anim = animation ? { type: animation, duration: 1000 } : icon?.animation;
---`;
};

/**
 * Generador principal del componente Astro
 */
export function generateAstroComponent(componentName: string): string {
  // Eliminamos caracteres conflictivos de la interpolación del generador
  const frontmatter = getAstroFrontmatter();
  const clientScript = getAstroClientScript();

  return `// Auto-generated by MasterSVG
${frontmatter}

{icon && (
  <svg
    viewBox={icon.viewBox}
    width={sizeValue}
    height={sizeValue}
    fill={color}
    class={className}
    data-animation={anim?.type}
    data-animation-duration={anim?.duration}
    data-animation-iteration={anim?.iteration}
    set:html={body}
  />
)}

${clientScript}
`;
}
