import { toPascalCase, getAnimationKeyframesString } from '../utils/componentHelpers';

/**
 * Genera la lógica de efectos y limpieza de SolidJS
 */
const getSolidLogic = () => `
  const icon = () => (icons as any)[props.name];
  const sizeVal = () => typeof props.size === 'number' ? \`\${props.size}px\` : (props.size || '1em');

  const body = () => {
    const data = icon();
    if (!data) return '';
    let b = data.body;
    if (props.variant && data.variants?.[props.variant]) {
      Object.entries(data.variants[props.variant]).forEach(([orig, repl]) => {
        const escaped = orig.replace(/[.*+?^$\${}()|[\\]\\\\]/g, '\\\\$&');
        b = b.replace(new RegExp(escaped, 'gi'), repl as string);
      });
    }
    return b;
  };

  createEffect(() => {
    if (!svgRef || !icon()) return;
    if (animPlayer) animPlayer.cancel();
    const config = props.animation ? { type: props.animation, duration: 1000 } : icon().animation;
    if (config && ANIMATION_KEYFRAMES[config.type]) {
      animPlayer = svgRef.animate(ANIMATION_KEYFRAMES[config.type], {
        duration: config.duration || 1000,
        iterations: Infinity
      });
    }
  });

  onCleanup(() => animPlayer?.cancel());`;

export function generateSolidComponent(componentName: string): string {
  const name = toPascalCase(componentName);

  // Constantes de escape para proteger la interpolación contra errores de ESLint/Parsing
  const dol = '$';
  const open = '{';
  const close = '}';

  return `// Auto-generated by MasterSVG
import { createEffect, onCleanup } from 'solid-js';
import { icons } from './svg-data';

${getAnimationKeyframesString()}

export const ${name} = (props: any) => {
  let svgRef: SVGSVGElement | undefined;
  let animPlayer: Animation | null = null;

  ${getSolidLogic()}

  return (
    <svg
      ref={svgRef}
      viewBox=${dol}${open}icon()?.viewBox${close}
      width=${dol}${open}sizeVal()${close}
      height=${dol}${open}sizeVal()${close}
      fill=${dol}${open}props.color || 'currentColor'${close}
      class=${dol}${open}props.class${close}
      style=${dol}${open}props.style${close}
      innerHTML=${dol}${open}body()${close}
    />
  );
};

export default ${name};`;
}
