/**
 * Utility functions for icon file manipulation
 */

/**
 * Generates an icon entry for icons.js file
 */
export function generateIconEntry(varName: string, iconName: string, body: string, viewBox: string = '0 0 24 24'): string {
  return `export const ${varName} = {
  name: '${iconName}',
  body: \`${body}\`,
  viewBox: '${viewBox}'
};`;
}

/**
 * Creates a regex pattern to match an existing icon export
 */
export function createIconExportPattern(varName: string): RegExp {
  return new RegExp(`export const ${varName} = \\{[\\s\\S]*?\\};`, 'g');
}

/**
 * Checks if an icon export exists in file content
 */
export function iconExportExists(content: string, varName: string): boolean {
  return content.includes(`export const ${varName}`);
}

/**
 * Replaces an existing icon export in file content
 */
export function replaceIconExport(content: string, varName: string, newEntry: string): string {
  const pattern = createIconExportPattern(varName);
  return content.replace(pattern, newEntry);
}

/**
 * Finds the position of the icons object in file content
 */
export function findIconsObjectPosition(content: string): number | null {
  const match = content.match(/export const icons = \{/);
  return match?.index ?? null;
}

/**
 * Extracts the content inside the icons object
 */
export function extractIconsObjectContent(content: string): string | null {
  const match = content.match(/export const icons = \{([^}]*)\}/);
  return match?.[1]?.trim() ?? null;
}

/**
 * Adds a new icon to the icons object
 */
export function addIconToIconsObject(content: string, varName: string): string {
  const objContent = extractIconsObjectContent(content);
  if (objContent === null) {
    return content;
  }
  
  const newIcons = objContent ? `${objContent},\n  ${varName}` : `\n  ${varName}\n`;
  return content.replace(/export const icons = \{([^}]*)\}/, `export const icons = {${newIcons}}`);
}

/**
 * Inserts an icon entry before the icons object
 */
export function insertIconBeforeObject(content: string, iconEntry: string, position: number): string {
  return content.slice(0, position) + iconEntry + '\n\n' + content.slice(position);
}

/**
 * Generates the initial icons.js file content
 */
export function generateNewIconsFileContent(varName: string, iconEntry: string): string {
  return `// Auto-generated by Icon Manager
// Do not edit manually

${iconEntry}

export const icons = {
  ${varName}
};
`;
}

/**
 * Updates or adds an icon to existing file content
 */
export function updateIconsFileContent(content: string, varName: string, iconEntry: string): string {
  // Check if icon already exists
  if (iconExportExists(content, varName)) {
    // Replace existing
    return replaceIconExport(content, varName, iconEntry);
  }
  
  // Find the icons object and add before it
  const position = findIconsObjectPosition(content);
  if (position !== null) {
    // Insert entry before icons object
    let updatedContent = insertIconBeforeObject(content, iconEntry, position);
    // Also add to the icons object
    updatedContent = addIconToIconsObject(updatedContent, varName);
    return updatedContent;
  }
  
  // Just append at the end
  return content + '\n\n' + iconEntry;
}

/**
 * Generates Web Component file header comment
 */
export function generateWebComponentHeader(tagName: string): string {
  return `// Auto-generated Web Component by Icon Manager
// Usage: <${tagName} name="icon-name"></${tagName}>
// With variant: <${tagName} name="icon-name" variant="dark-theme"></${tagName}>
// With animation: <${tagName} name="icon-name" animation="spin"></${tagName}>
// Import this file in your HTML: <script type="module" src="./path/to/icon.js"></script>`;
}

/**
 * Converts component name to valid custom element tag name
 * Custom elements MUST have a hyphen
 */
export function componentNameToTagName(componentName: string): string {
  // Convert PascalCase/camelCase to kebab-case
  let tagName = componentName
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .toLowerCase();
  
  // Custom elements MUST have a hyphen - if none, add suffix
  if (!tagName.includes('-')) {
    tagName = `${tagName}-icon`;
  }
  
  return tagName;
}

/**
 * Generates variants.js file content
 */
export function generateVariantsFile(variants: Record<string, Record<string, string[]>>, defaults: Record<string, string>): string {
  return `// Auto-generated by Icon Manager
// Do not edit manually

export const Variants = ${JSON.stringify(variants, null, 2)};

export const defaultVariants = ${JSON.stringify(defaults, null, 2)};
`;
}

/**
 * Generates animations.js file content
 */
export function generateAnimationsFile(animations: Record<string, { type: string; duration: number; timing: string; iteration: string }>): string {
  return `// Auto-generated by Icon Manager
// Do not edit manually

export const animations = ${JSON.stringify(animations, null, 2)};
`;
}

/**
 * Parses an existing icons.js file to extract icon names
 */
export function parseIconNames(content: string): string[] {
  const names: string[] = [];
  const pattern = /export const (\w+) = \{[\s\S]*?name:\s*['"]([^'"]+)['"]/g;
  let match;
  while ((match = pattern.exec(content)) !== null) {
    names.push(match[2]);
  }
  return names;
}

/**
 * Parses an existing icons.js file to extract variable names
 */
export function parseIconVariables(content: string): string[] {
  const variables: string[] = [];
  const pattern = /export const (\w+) = \{[\s\S]*?name:/g;
  let match;
  while ((match = pattern.exec(content)) !== null) {
    variables.push(match[1]);
  }
  return variables;
}

/**
 * Validates if content looks like a valid icons.js file
 */
export function isValidIconsFile(content: string): boolean {
  return content.includes('export const icons = {') || 
         content.includes('export const ') && content.includes('body:');
}

/**
 * Counts the number of icons in an icons.js file
 */
export function countIconsInFile(content: string): number {
  return parseIconVariables(content).length;
}

/**
 * Removes an icon from the icons.js file content
 */
export function removeIconFromFile(content: string, varName: string): string {
  // Remove the export const declaration
  const pattern = createIconExportPattern(varName);
  let result = content.replace(pattern, '');
  
  // Remove from icons object
  // Handle both "varName," and ",varName" and just "varName"
  result = result.replace(new RegExp(`\\s*${varName}\\s*,`, 'g'), '');
  result = result.replace(new RegExp(`,\\s*${varName}\\s*`, 'g'), '');
  result = result.replace(new RegExp(`\\{\\s*${varName}\\s*\\}`, 'g'), '{}');
  
  // Clean up extra newlines
  result = result.replace(/\n{3,}/g, '\n\n');
  
  return result;
}

/**
 * Color presets for icon picker
 */
export const COLOR_PRESETS = [
  { color: '#ffffff', name: 'White' },
  { color: '#000000', name: 'Black' },
  { color: '#3b82f6', name: 'Blue' },
  { color: '#10b981', name: 'Green' },
  { color: '#f59e0b', name: 'Orange' },
  { color: '#ef4444', name: 'Red' },
  { color: '#8b5cf6', name: 'Purple' },
  { color: '#ec4899', name: 'Pink' }
];

/**
 * Generates color preset buttons HTML
 */
export function generateColorPresetButtons(activeColor: string = '#ffffff'): string {
  return COLOR_PRESETS.map(preset => {
    const isActive = preset.color === activeColor ? ' active' : '';
    return `<button class="color-preset${isActive}" style="background: ${preset.color}" data-color="${preset.color}" title="${preset.name}"></button>`;
  }).join('\n      ');
}
